### ISSUE TITLE
OS detection fails on vagrant 1.7.2 / windows

### ISSUE THREAD

**Issue by timidri** [tmatilai/vagrant-proxyconf#110] opened 2015-03-09 12:44 UTC
See https://github.com/tmatilai/vagrant-proxyconf/blob/master/lib/vagrant-proxyconf/action/configure_env_proxy.rb#L44:

``` ruby
def windows_guest?
  @machine.config.vm.guest.eql?(:windows)
end
```

This test fails on vagrant 1.7.2 / windows because `@machine.config.vm.guest.eql?(:windows)` returns false. while vagrant succesfully autodetects the OS to be windows.

**Comment by tmatilai** [comment] 2015-03-11 14:31
Ah, this was written before Windows guest support was included into Vagrant core. We should now ask the guest type directly from Vagrant (and fallback to this on older Vagrant versions).

**Comment by timidri** [comment] 2015-03-12 16:33
Yes, i tried to find in the documentation how to do it so I could offer a pull request, but I wasn't able to find it. :-(

**Comment by codylane** [comment] 2019-03-31 18:15
Closing out this issue case windows support seems to be working.  Please re-open if this is still an issue and provide details on how to reproduce.

**Closed by codylane** 2019-03-31 18:15 UTC
