### ISSUE TITLE
Trigger proxy_conf on vagrant ssh

### ISSUE THREAD

**Issue by hinstef** [tmatilai/vagrant-proxyconf#185] opened 2019-02-14 13:42 UTC
I'm installing all sorts of packages like docker, python and npm via ansible. So when I do `vagrant up` on a fresh machine the stuff is installed. When I log in with `vagrant ssh` after the provisioning is done  none of the proxies are set since proxyconf was only triggered once on the first `vagrant up` when it was still dealing with an empty base image.
The only way I found thus far getting around this issue is to provision again after the first provisioning.
So what would be great if proxyconf would also set the proxies when logging in via `vagrant ssh`

**Comment by codylane** [comment] 2019-02-15 05:38
@hinstef - I apologize you are having issues with this plugin.  If you'd like further help I'd highly recommend you provide your Vagrantfile and steps needed to reproduce this problem.  Without those details and examples demonstrating the behavior you are seeing there isn't much we can do to help you or provide a solution.

**Comment by codylane** [comment] 2019-02-28 00:39
Closing out issue as I cannot reproduce nor is there enough information to troubleshoot.

**Closed by codylane** 2019-02-28 00:39 UTC
